Repository occmundial/occ-atomic, pull requests merged in 2019-10, with the labels that each got.

#21 New logo icons
  lib/subatomic/icons.js
  lib/subatomic/icons/occDart.js
  lib/subatomic/icons/occHorizontal.js
  lib/subatomic/icons/occVertical.js
  src/config/componentData.js
  src/docs/examples/NavTab/Example1.js
  src/docs/examples/NavTab/Example3.js
  src/docs/examples/NavTab/Example4.js
Labels: ready for review

#22 Fix/slide down
  lib/SlideDown/SlideDown.js
  lib/SlideDown/SlideDown.test.js
  lib/SlideDown/__snapshots__/SlideDown.test.js.snap
  src/config/componentData.js
  src/docs/examples/SlideDown/Example4.js
  src/docs/examples/SlideDown/Example5.js
Labels: bug, ready for review

#23 Slide Toggle Name
  lib/SlideDown/__snapshots__/SlideDown.test.js.snap
  lib/SlideToggle/SlideToggle.js
  src/config/componentData.js
  src/docs/examples/SlideToggle/Example3.js
Labels: enhancement, ready for review

#24 Changes in SlideDown component
  lib/SlideDown/SlideDown.js
  lib/SlideToggle/__snapshots__/SlideToggle.test.js.snap
  src/config/componentData.js
  src/docs/examples/SlideDown/Example5.js
Labels: ready for review

#25 Toaster component
  lib/Toaster/Toast/Toast.js
  lib/Toaster/Toast/index.js
  lib/Toaster/Toast/styles.js
  lib/Toaster/Toaster.js
  lib/Toaster/Toaster.test.js
  lib/Toaster/__snapshots__/Toaster.test.js.snap
  lib/Toaster/functions.js
  lib/Toaster/index.js
  lib/Toaster/styles.js
  lib/index.js
  src/config/componentData.js
  src/config/componentOrdering.js
  src/docs/examples/Toaster/Example1.js
  src/docs/examples/Toaster/Example2.js
  src/docs/examples/Toaster/Example3.js
  src/docs/examples/Toaster/Example4.js
  src/docs/examples/Toaster/Example5.js
  src/docs/examples/Toaster/Example6.js
  src/docs/examples/Toaster/Example7.js
Labels: ready for review
