Repository occmundial/occ-atomic, pull requests merged in 2020-04, with the labels that each got.

#62 #Banner
  CHANGELOG.md
  lib/Banner/Banner.js
  lib/Banner/Banner.test.js
  lib/Banner/__snapshots__/Banner.test.js.snap
  lib/Banner/index.js
  lib/Banner/styles.js
  lib/index.js
  package-lock.json
  package.json
  src/config/componentData.js
  src/config/componentOrdering.js
  src/docs/examples/Banner/Example1.js
Labels: enhancement

#65 Autocomplete recent
  .prettierrc
  lib/Autocomplete/Autocomplete.js
  lib/Droplist/Droplist.js
  lib/Droplist/styles.js
  package.json
  src/docs/examples/Autocomplete/Example4.js
  src/docs/examples/Autocomplete/Example5.js
Labels: ready for review

#66 NEW VERSION 1.13.17
  .prettierrc
  CHANGELOG.md
  lib/Autocomplete/Autocomplete.js
  lib/Droplist/Droplist.js
  lib/Droplist/styles.js
  package.json
  src/docs/examples/Autocomplete/Example4.js
  src/docs/examples/Autocomplete/Example5.js
Labels: ready for review

#67 Extra content droplist
  CHANGELOG.md
  lib/Autocomplete/__snapshots__/Autocomplete.test.js.snap
  lib/Droplist/Droplist.js
  lib/Droplist/__snapshots__/Droplist.test.js.snap
  lib/Droplist/styles.js
  package.json
  src/docs/examples/Autocomplete/Example5.js
Labels: ready for review

#64 Text Mobile at Banner
  CHANGELOG.md
  lib/Banner/Banner.js
  lib/Banner/__snapshots__/Banner.test.js.snap
  src/config/componentData.js
  src/docs/examples/Banner/Example1.js
Labels: enhancement

#69 Fix/normalize bug
  CHANGELOG.md
  lib/Droplist/__snapshots__/Droplist.test.js.snap
  lib/Droplist/functions.js
  package-lock.json
  package.json
  src/config/componentData.js
  yarn.lock
Labels: bug, ready for review

#71 Deploy Version 1.13.19
  CHANGELOG.md
  lib/Banner/Banner.js
  lib/Banner/__snapshots__/Banner.test.js.snap
  lib/Droplist/__snapshots__/Droplist.test.js.snap
  lib/Droplist/functions.js
  package-lock.json
  package.json
  src/config/componentData.js
  src/docs/examples/Banner/Example1.js
  yarn.lock
Labels: ready for review

#72 Fix pills text
  CHANGELOG.md
  lib/Pill/Choice/Choice.js
  lib/Pill/Choice/styles.js
  lib/Pill/__snapshots__/Pill.test.js.snap
  lib/Pill/styles.js
  package.json
  src/config/componentData.js
Labels: ready for review
